print("Bem vindo ao gerenciador de bibliotecas!")

escolha_do_usuario = print("O que você deseja fazer?")
print("1 - Adicionar novo livro")
print("2 - Remover livro existente")
print("3 - Atualizar informações de um livro")
print("4 - Listar todos os livros disponíveis")
print("-"*60)
print("5 - Adicionar novo usuário")
print("6 - Remover usuário existente")
print("7 - Atualizar informações de um usuário")
print("8 - Listar todos os usuários registrados")
